import { EXPORT_CATEGORIES } from "@/lib/export-categories";

export const LENA = {
  agency: {
    name: "LENA Agency",
    nameKo: "레나에이전시",
    tagline: "Partnerships beyond borders",
    taglineKo: "국경을 넘는 파트너십",
    lead: "Bringing outstanding ideas to the world.",
    leadKo: "탁월한 아이디어를 세계에 전합니다.",
    // Contact email is server-only (see /api/contact) — never ship to client HTML/JS.
    instagram: "https://www.instagram.com/lena.agency",
    address: "Seoul, Republic of Korea",
    addressKo: "서울특별시",
  },

  stats: [
    { value: "1,000+", label: "Contracts managed", labelKo: "관리 계약" },
    { value: "200+", label: "Publishing partners", labelKo: "출판 파트너" },
    { value: "25+", label: "Years of experience", labelKo: "에이전트 경력" },
  ],

  /* 수출: 정적 폴백 (Google Sheet 미설정·오류 시). 시트 연동 후 시트가 우선. */
  exportTitles: [
    {
      id: "teacher-speech-skills",
      title: "The Teacher's Art of Words That Protect You Without Getting Hurt",
      titleKo: "상처받지 않으면서 나를 지키는 교사의 말 기술",
      author: "김성효",
      authorEn: "Seonghyo Kim",
      category: "professional",
      categoryLabel: "Professional",
      categoryLabelKo: "직업/실무",
      categories: ["professional", "series"],
      categoryLabels: ["Professional", "Series"],
      categoryLabelsKo: ["직업/실무", "시리즈"],
      series: "Seonghyo-ssaem's Teacher Mentoring",
      seriesKo: "성효 쌤의 교사 멘토링",
      publisher: "빅피시",
      publisherEn: "Big Fish",
      country: "Korea",
      format: ["print", "ebook"],
      rightsNote: "World rights available (Taiwan licensed)",
      rightsNoteKo: "세계 판권 가능 (대만 계약 완료)",
      territories: "Taiwan licensed · other territories available",
      territoriesKo: "대만 계약 · 기타 지역 가능",
      rightsSold: "Traditional Chinese",
      rightsSoldKo: "번체 중국어",
      pages: 268,
      pubYear: 2024,
      age: "",
      coverCopy:
        "36 scripts for facing parents with confidence · Mentor to hundreds of thousands of Korean teachers · 27 years of classroom know-how · Seonghyo-ssaem’s Teacher Mentoring series",
      coverCopyKo:
        "당당하게 학부모와 마주하기 위한 민원 대응법 36 · 대한민국 45만 교사들의 멘토 · 27년 차 현직 교사 노하우 · 성효 쌤의 교사 멘토링 1",
      synopsis:
        "A practical guide for teachers on parent communication and complaint handling—36 field-tested response scripts drawn from real classroom and school-gate situations. How to stay calm, set boundaries, and protect yourself while remaining professional—without getting hurt in the process.",
      synopsisKo:
        "교육 현장의 실제 사례를 바탕으로, 상처받지 않으면서도 나를 지키는 교사의 말과 태도를 정리한 실전 가이드. 『교사의 말 연습』의 후속 멘토링으로, 학부모 상담·민원 상황에서 감정을 지키며 명확히 대응하는 말 기술을 제시합니다.",
      authorBio:
        "Seonghyo Kim is a bestselling author and 29-year educator who lectures and consults for students, parents, and teachers. She currently serves as an elementary school vice principal and shares practical education know-how with teachers and parents nationwide.",
      authorBioKo:
        "학생·학부모·교사를 대상으로 강연과 상담을 하는 베스트셀러 작가이자 29년 차 교육자. 현재 초등학교 교감으로 재직하며, 전국의 교사와 학부모에게 교육 노하우를 전하고 있다.",
      colors: ["#7ec8d4", "#2a9d8f"],
      cover: "/covers/teacher-communication-skills.png",
      featured: true,
      new: true,
    },
    {
      id: "harvard-secrets",
      title: "Secrets from the Top 1% at Harvard",
      titleKo: "하버드 상위 1%의 비밀",
      author: "정주영",
      authorEn: "Juyoung Jung",
      category: "self-help",
      categoryLabel: "Self-help",
      categoryLabelKo: "자기계발",
      categories: ["self-help"],
      categoryLabels: ["Self-help"],
      categoryLabelsKo: ["자기계발"],
      publisher: "한경비피",
      publisherEn: "KED&BP",
      country: "Korea",
      format: ["print", "ebook"],
      rightsNote: "World rights available (selected territories sold)",
      rightsNoteKo: "세계 판권 가능 (일부 지역 계약 완료)",
      territories: "Vietnam licensed · other territories available",
      territoriesKo: "베트남 계약 · 기타 지역 가능",
      rightsSold: "Vietnamese",
      rightsSoldKo: "베트남어",
      pages: 272,
      pubYear: 2021,
      age: "",
      coverCopy:
        "Study habits and mindset from Harvard’s top performers",
      coverCopyKo:
        "하버드 상위 1%가 지키는 공부와 태도의 비밀",
      synopsis:
        "Study habits and mindset insights from high-achieving Harvard students—originally published in Korea. A practical self-help title for readers who want elite-level learning routines in everyday language.",
      synopsisKo:
        "하버드 상위권 학생들의 학습 습관과 마인드셋을 정리한 자기계발·학습법 논픽션. 성과를 내는 공부 문화를 한국 독자에게 친숙한 언어로 전합니다.",
      authorBio:
        "Juyoung Jung writes on learning habits, mindset, and high-performance study culture for Korean and international readers. This title gathers practical insights associated with elite academic environments and presents them in an accessible self-help style.",
      authorBioKo:
        "정주영은 학습 습관과 마인드셋, 성과를 내는 공부 문화를 다루는 저자다. 이 책에서는 하버드 상위권 학생들의 사례를 바탕으로, 독자가 바로 적용할 수 있는 학습법과 태도 이야기를 풀어낸다.",
      colors: ["#a4161a", "#660708"],
      featured: true,
      new: false,
    },
    {
      id: "korean-folk-reimagined",
      title: "Korean Folktales, Reimagined",
      titleKo: "다시 쓰는 한국 설화",
      author: "샘플 저자",
      authorEn: "Sample Korean Author",
      category: "fiction",
      categoryLabel: "Fiction",
      categoryLabelKo: "소설",
      publisher: "한국 출판사",
      publisherEn: "Korean Publisher",
      country: "Korea",
      format: ["print", "ebook"],
      rightsNote: "World English & other languages available",
      rightsNoteKo: "영어 포함 세계 판권 가능",
      territories: "All territories available",
      territoriesKo: "전 지역 가능",
      pages: 220,
      pubYear: 2025,
      age: "Adult / YA",
      coverCopy:
        "Classic Korean tales, retold for today’s readers",
      coverCopyKo:
        "오늘을 사는 우리를 위한, 다시 쓰는 한국 설화",
      synopsis:
        "Classic Korean tales retold for a global readership—myth, humor, and a modern voice that bridges tradition and the present.",
      synopsisKo:
        "한국 고전 설화를 세계 독자를 위해 다시 쓴 작품. 신화와 유머, 현대적 목소리를 한 데 담았습니다.",
      authorBio:
        "A Korean fiction writer reworking classic folklore for contemporary audiences. Their stories blend myth, humor, and a modern narrative voice aimed at both local and global readers. (Sample author profile — replace with final bio.)",
      authorBioKo:
        "한국 고전 설화를 현대적으로 다시 쓰는 소설가. 신화와 유머, 오늘의 목소리를 섞어 국내외 독자에게 말을 건다. (샘플 저자 소개 — 최종 바이오로 교체 가능)",
      colors: ["#9b2226", "#ae2012"],
      featured: true,
      new: true,
    },
    {
      id: "seoul-quiet-hours",
      title: "Seoul, Quiet Hours",
      titleKo: "서울의 고요한 시간",
      author: "샘플 저자",
      authorEn: "Sample Author",
      category: "nonfiction",
      categoryLabel: "Nonfiction",
      categoryLabelKo: "비소설",
      categories: ["nonfiction"],
      categoryLabels: ["Nonfiction"],
      categoryLabelsKo: ["비소설"],
      publisher: "한국 출판사",
      publisherEn: "Korean Publisher",
      country: "Korea",
      format: ["print"],
      rightsNote: "World rights available",
      rightsNoteKo: "세계 판권 가능",
      territories: "All territories available",
      territoriesKo: "전 지역 가능",
      pages: 208,
      pubYear: 2024,
      age: "",
      coverCopy:
        "Quiet cafés, side streets, and the softer side of Seoul",
      coverCopyKo:
        "카페와 골목에서 만나는, 서울의 고요한 시간",
      synopsis:
        "A lyrical guide to the city's quieter corners—cafés, walks, and the rhythm of ordinary days for readers who want Seoul beyond the landmarks.",
      synopsisKo:
        "카페와 골목, 일상의 리듬을 담은 서울 에세이. 도시의 고요한 면을 세계에 소개합니다.",
      authorBio:
        "An essayist exploring everyday Seoul—quiet cafés, side streets, and the pace of ordinary days. Their writing invites international readers into the city’s softer rhythms. (Sample author profile — replace with final bio.)",
      authorBioKo:
        "서울의 카페와 골목, 일상 리듬을 에세이로 담아내는 작가. 도시의 고요한 풍경을 섬세한 시선으로 기록한다. (샘플 저자 소개 — 최종 바이오로 교체 가능)",
      colors: ["#264653", "#2a9d8f"],
      featured: true,
      new: true,
    },
    {
      id: "little-tiger-big-dream",
      title: "Little Tiger, Big Dream",
      titleKo: "작은 호랑이, 큰 꿈",
      author: "샘플 작가",
      authorEn: "Sample Illustrator",
      category: "picturebook",
      categoryLabel: "Picture Books",
      categoryLabelKo: "그림책",
      publisher: "한국 아동 출판사",
      publisherEn: "Korean Children's House",
      country: "Korea",
      format: ["print"],
      rightsNote: "World rights available · co-edition welcome",
      rightsNoteKo: "세계 판권 가능 · 공동판형 환영",
      territories: "All territories available",
      territoriesKo: "전 지역 가능",
      pages: 36,
      pubYear: 2025,
      age: "3–7",
      coverCopy:
        "Courage, friendship, and a dream bigger than the mountain",
      coverCopyKo:
        "용기와 우정, 산을 넘는 작은 호랑이의 큰 꿈",
      synopsis:
        "A warm picture book about courage, friendship, and dreaming beyond the mountain—ideal for co-editions and international children’s lists.",
      synopsisKo:
        "용기와 우정, 산을 넘는 꿈을 그린 따뜻한 그림책. 공동판형·수출 상담 가능.",
      authorBio:
        "A Korean picture-book creator focused on stories of courage, friendship, and growing up. Their work is well suited to co-editions and international children’s lists. (Sample author profile — replace with final bio.)",
      authorBioKo:
        "용기와 우정, 성장의 이야기를 그리는 그림책 작가. 공동판형·해외 아동 목록에 잘 맞는 따뜻한 시선으로 알려져 있다. (샘플 저자 소개 — 최종 바이오로 교체 가능)",
      colors: ["#e76f51", "#f4a261"],
      featured: true,
      new: true,
    },
    {
      id: "kimchi-economics",
      title: "Kimchi Economics",
      titleKo: "김치 경제학",
      author: "샘플 저자",
      authorEn: "Sample Author",
      category: "business",
      categoryLabel: "Business/Economics",
      categoryLabelKo: "경제경영",
      categories: ["business"],
      categoryLabels: ["Business/Economics"],
      categoryLabelsKo: ["경제경영"],
      publisher: "한국 출판사",
      publisherEn: "Korean Publisher",
      country: "Korea",
      format: ["print", "ebook"],
      rightsNote: "World rights available",
      rightsNoteKo: "세계 판권 가능",
      territories: "All territories available",
      territoriesKo: "전 지역 가능",
      pages: 256,
      pubYear: 2023,
      age: "",
      coverCopy:
        "What kimchi teaches about markets, brands, and resilience",
      coverCopyKo:
        "김치 한 포기에 담긴 시장·브랜드·회복탄력성 이야기",
      synopsis:
        "What Korean food culture teaches about markets, branding, and resilience—sharp, readable nonfiction for global business and culture readers.",
      synopsisKo:
        "한식 문화에서 읽는 시장·브랜딩·회복탄력성. 해외 독자에게 친숙한 한국 경제·문화 논픽션.",
      authorBio:
        "A nonfiction writer on Korean food culture, markets, and branding. Their work connects everyday culture to larger stories about resilience and the economy. (Sample author profile — replace with final bio.)",
      authorBioKo:
        "한식 문화와 시장·브랜딩을 연결해 쓰는 논픽션 저자. 일상 문화 속에서 경제와 회복탄력성의 이야기를 풀어낸다. (샘플 저자 소개 — 최종 바이오로 교체 가능)",
      colors: ["#bc4749", "#6a040f"],
      featured: false,
      new: false,
    },
    {
      id: "mindful-seoul",
      title: "One-Minute Mindfulness from Seoul",
      titleKo: "서울에서 온 마음챙김 1분",
      author: "샘플 저자",
      authorEn: "Sample Author",
      category: "lifestyle",
      categoryLabel: "Lifestyle/Health",
      categoryLabelKo: "실용/건강",
      categories: ["lifestyle"],
      categoryLabels: ["Lifestyle/Health"],
      categoryLabelsKo: ["실용/건강"],
      publisher: "한국 출판사",
      publisherEn: "Korean Publisher",
      country: "Korea",
      format: ["print", "ebook", "audio"],
      rightsNote: "World rights available",
      rightsNoteKo: "세계 판권 가능",
      territories: "All territories available",
      territoriesKo: "전 지역 가능",
      pages: 160,
      pubYear: 2025,
      age: "",
      coverCopy:
        "Sixty one-minute mindfulness practices for a fast city",
      coverCopyKo:
        "바쁜 서울을 위한 마음챙김 1분 × 60",
      synopsis:
        "Sixty tiny practices for busy lives—born in one of the world's fastest cities. A compact Korean wellness package for international lists.",
      synopsisKo:
        "바쁜 도시를 위한 아주 짧은 마음챙김 60. 한국 웰니스 콘텐츠의 수출형 패키지.",
      authorBio:
        "A wellness writer offering short, practical mindfulness practices for busy urban life. Their work packages Korean wellness culture for international readers. (Sample author profile — replace with final bio.)",
      authorBioKo:
        "바쁜 도시 일상을 위한 짧은 마음챙김 실천을 전하는 웰니스 저자. 한국 웰니스 콘텐츠를 해외 독자도 쓰기 쉽게 풀어쓴다. (샘플 저자 소개 — 최종 바이오로 교체 가능)",
      colors: ["#40916c", "#1b4332"],
      featured: false,
      new: true,
    },
  ],

  exportCategories: EXPORT_CATEGORIES,

  /* 수입 베스트셀러 30: 계약목록 누적판매부수 기준 (종이책, 갱신 병합) */
  /* 수입 베스트셀러 30: 누적판매 기준, 대교 제외 */
  importHighlights: [
    {
      id: "best-01-petite-philosophie-de-la-mer",
      title: "PETITE PHILOSOPHIE DE LA MER (A Short Philosophy of the Sea)",
      titleKo: "모든 삶은 흐른다",
      author: "Laurence Devillairs",
      rightsHolder: "2 Seas Agency (EDLM)",
      koreanPublisher: "피카",
      country: "France",
      pubYear: 2023,
      cumSold: 85117,
      cover: "/covers/toutes-les-vies-coulent.png",
      colors: ["#c41e3a", "#5c1524"],
    },
    {
      id: "best-02-future-after-covid-the",
      title: "FUTURE AFTER COVID, THE",
      titleKo: "코로나 이후의 세계",
      author: "Jason Schenker",
      rightsHolder: "Rightol Media (Prestige Professional Publishing, LLC)",
      koreanPublisher: "다빈치하우스",
      country: "USA",
      pubYear: 2020,
      cumSold: 28490,
      cover: "/covers/future-after-covid.png",
      colors: ["#9b1830", "#3b0f18"],
    },
    {
      id: "best-03-don-t-believe-everything-you",
      title: "DON'T BELIEVE EVERYTHING YOU THINK",
      titleKo: "당신이 생각하는 모든 것을 믿지 말라",
      author: "Joseph Nguyen",
      rightsHolder: "Dropcap (author)",
      koreanPublisher: "서삼독",
      country: "USA",
      pubYear: 2023,
      cumSold: 24657,
      cover: "/covers/dont-believe-everything.png",
      colors: ["#264653", "#1d3557"],
    },
    {
      id: "best-04-adventures-in-philosophy",
      title: "ADVENTURES IN PHILOSOPHY",
      titleKo: "철학의숲",
      author: "Brenden O'Donoghue",
      rightsHolder: "Print Company (Gill Books)",
      koreanPublisher: "포레스트북스",
      country: "Ireland",
      pubYear: 2020,
      cumSold: 21366,
      cover: "/covers/philosophy-forest.png",
      colors: ["#2a9d8f", "#1b4332"],
    },
    {
      id: "best-05-gu-rir-la-vie-par-la-philoso",
      title: "Guérir la vie par la philosophie",
      titleKo: "철학의 쓸모",
      author: "Laurence Devillairs",
      rightsHolder: "Humensis",
      koreanPublisher: "피카",
      country: "France",
      pubYear: 2024,
      cumSold: 19276,
      cover: "/covers/philosophy-usefulness.png",
      colors: ["#457b9d", "#1d3557"],
    },
    {
      id: "best-06-voor-elkaar-little-book-of-c",
      title: "Voor elkaar (LITTLE BOOK OF CARING)",
      titleKo: "매일매일 행복해",
      author: "Francesca Pirrone",
      rightsHolder: "Clavis",
      koreanPublisher: "피카주니어",
      country: "Netherland",
      pubYear: 2022,
      cumSold: 18328,
      cover: "/covers/every-day-happy.png",
      colors: ["#e76f51", "#9b2226"],
    },
    {
      id: "best-07-anxious-perfectionist-the",
      title: "ANXIOUS PERFECTIONIST, THE",
      titleKo: "불안한 완벽주의자를 위한 책",
      author: "Clarissa Ong and Michael Twohig",
      rightsHolder: "New Harbinger",
      koreanPublisher: "수오서재",
      country: "USA",
      pubYear: 2023,
      cumSold: 15834,
      cover: "/covers/anxious-perfectionist.png",
      colors: ["#6d597a", "#355070"],
    },
    {
      id: "best-08-psychology-of-procrastinatio",
      title: "PSYCHOLOGY OF PROCRASTINATION, THE",
      titleKo: "게으른 완벽주의자를 위한 심리학",
      author: "Dr. Hayden Finch",
      rightsHolder: "Callisto Media",
      koreanPublisher: "시크릿하우스",
      country: "USA",
      pubYear: 2022,
      cumSold: 14918,
      cover: "/covers/psychology-procrastination.png",
      colors: ["#bc6c25", "#6a040f"],
    },
    {
      id: "best-09-time-off-by-john-fitch-and-m",
      title: "TIME OFF by John Fitch and Max Frenzel",
      titleKo: "이토록 멋진 휴식",
      author: "John Fitch and Max Frenzel",
      rightsHolder: "Dropcap (Rest Ethic Ventures)",
      koreanPublisher: "현대지성",
      country: "USA",
      pubYear: 2024,
      cumSold: 14570,
      cover: "/covers/time-off.png",
      colors: ["#40916c", "#1b4332"],
    },
    {
      id: "best-10-a-cloud-a-day",
      title: "A CLOUD A DAY",
      titleKo: "날마다 구름 한 점",
      author: "Gavin Pretor",
      rightsHolder: "Marco Rodino Agency (Pavilion)",
      koreanPublisher: "김영사",
      country: "UK",
      pubYear: 2021,
      cumSold: 13778,
      cover: "/covers/cloud-a-day.png",
      colors: ["#3d5a80", "#1d3557"],
    },
    {
      id: "best-11-you-happier",
      title: "YOU, HAPPIER",
      titleKo: "마음이 아니라 뇌가 불안한 겁니다",
      author: "Daniel G. Amen",
      rightsHolder: "Tyndale House Publishers",
      koreanPublisher: "위즈덤하우스",
      country: "USA",
      pubYear: 2023,
      cumSold: 10771,
      cover: "/covers/you-happier.png",
      colors: ["#7b2cbf", "#5a189a"],
    },
    {
      id: "best-12-52-week-mental-health-journa",
      title: "52-WEEK MENTAL HEALTH JOURNAL",
      titleKo: "하루 한 줄 마음챙김 일기",
      author: "Cynthia Catchings",
      rightsHolder: "Callisto Media",
      koreanPublisher: "현대지성",
      country: "USA",
      pubYear: 2023,
      cumSold: 10464,
      cover: "/covers/mental-health-journal.png",
      colors: ["#0077b6", "#03045e"],
    },
    {
      id: "best-13-voor-jou-just-for-you",
      title: "Voor jou (JUST FOR YOU)",
      titleKo: "너만을 위한 선물",
      author: "Francesca Pirrone",
      rightsHolder: "Clavis",
      koreanPublisher: "피카주니어",
      country: "Netherland",
      pubYear: 2022,
      cumSold: 10065,
      cover: "/covers/just-for-you.png",
      colors: ["#d62828", "#003049"],
    },
    {
      id: "best-14-the-gratitude-project-edited",
      title: "THE GRATITUDE PROJECT, edited",
      titleKo: "감사의 재발견",
      author: "Jeremy Adam Smith, Kira M. Newman, Jason Marsh and Dacher Keltner",
      rightsHolder: "New Harbinger",
      koreanPublisher: "현대지성",
      country: "USA",
      pubYear: 2024,
      cumSold: 10035,
      cover: "/covers/gratitude-project.png",
      colors: ["#606c38", "#283618"],
    },
    {
      id: "best-15-colours-of-film",
      title: "COLOURS OF FILM",
      titleKo: "컬러의 세계",
      author: "Charles Bramesco",
      rightsHolder: "Quarto",
      koreanPublisher: "다산",
      country: "UK",
      pubYear: 2024,
      cumSold: 7362,
      cover: "/covers/colours-of-film.png",
      colors: ["#f4a261", "#e76f51"],
    },
    {
      id: "best-16-fiat-standard-the",
      title: "FIAT STANDARD, THE",
      titleKo: "더 피아트 스탠다드",
      author: "Saifedean Ammous",
      rightsHolder: "Avintanio Consulting Limited (Saif)",
      koreanPublisher: "다산",
      country: "Jordan",
      pubYear: 2024,
      cumSold: 7000,
      cover: "/covers/fiat-standard.png",
      colors: ["#c41e3a", "#5c1524"],
    },
    {
      id: "best-17-glow-written",
      title: "GLOW written",
      titleKo: "글로우",
      author: "​Noelia Gonzalez and",
      rightsHolder: "Lucky Cat Publishing Limited (Magic Cat)",
      koreanPublisher: "피카주니어",
      country: "UK",
      pubYear: 2024,
      cumSold: 6912,
      cover: "/covers/glow.png",
      colors: ["#9b1830", "#3b0f18"],
    },
    {
      id: "best-18-into-the-impossible-think-li",
      title: "INTO THE IMPOSSIBLE: Think Like a Nobel Prize Winner",
      titleKo: "물리학자는 두뇌를 믿지 않는다",
      author: "Brian Keating",
      rightsHolder: "Dropcap (Scribe Media)",
      koreanPublisher: "다산",
      country: "USA",
      pubYear: 2024,
      cumSold: 6732,
      cover: "/covers/into-the-impossible.png",
      colors: ["#264653", "#1d3557"],
    },
    {
      id: "best-19-english-name-the-seller-of-h",
      title: "Продавача на омраза (English name: The Seller of Hatred) written",
      titleKo: "미움을 파는 고슴도치",
      author: "Слави Стоев and",
      rightsHolder: "Rightol Media (Robertino Publishing House)",
      koreanPublisher: "다봄",
      country: "Bulgaria",
      pubYear: 2021,
      cumSold: 6161,
      cover: "/covers/seller-of-hatred.png",
      colors: ["#2a9d8f", "#1b4332"],
    },
    {
      id: "best-20-soul-in-the-game",
      title: "SOUL IN THE GAME",
      titleKo: "죽음은 통제할 수 없지만 인생은 설계할 수 있다",
      author: "Vitaliy Katsenelson",
      rightsHolder: "Harriman House",
      koreanPublisher: "필름",
      country: "UK",
      pubYear: 2025,
      cumSold: 6042,
      cover: "/covers/soul-in-the-game.png",
      colors: ["#457b9d", "#1d3557"],
    },
    {
      id: "best-21-brian-the-dancing-lion",
      title: "BRIAN THE DANCING LION",
      titleKo: "춤추는 사자 브라이언",
      author: "Tom Tinn",
      rightsHolder: "Capstone",
      koreanPublisher: "피카주니어",
      country: "USA",
      pubYear: 2022,
      cumSold: 5415,
      cover: "/covers/dancing-lion-brian.png",
      colors: ["#e76f51", "#9b2226"],
    },
    {
      id: "best-22-little-dinosaurs-big-feeling",
      title: "LITTLE DINOSAURS, BIG FEELINGS (formerly DR. DIPLO'S GUIDE TO FEELINGS) written",
      titleKo: "어서 오세요, 공룡 박사님의 마음 상담소",
      author: "Swapna Haddow and",
      rightsHolder: "Lucky Cat Publishing Limited (Magic Cat)",
      koreanPublisher: "피카주니어",
      country: "UK",
      pubYear: 2025,
      cumSold: 5151,
      cover: "/covers/dinosaur-doctor.png",
      colors: ["#6d597a", "#355070"],
    },
    {
      id: "best-23-garbage-guts",
      title: "GARBAGE GUTS",
      titleKo: "쓰레기괴물",
      author: "Emily S Smith and Heidi Cooper",
      rightsHolder: "BK Agency (Larrikin)",
      koreanPublisher: "맛있는책",
      country: "Australia",
      pubYear: 2021,
      cumSold: 4899,
      cover: "/covers/garbage-guts.png",
      colors: ["#bc6c25", "#6a040f"],
    },
    {
      id: "best-24-parentshift",
      title: "PARENTSHIFT",
      titleKo: "사랑받은 아이는 흔들리지 않는다",
      author: "—",
      rightsHolder: "Sylvia Hayse",
      koreanPublisher: "빌리버튼",
      country: "USA",
      pubYear: 2022,
      cumSold: 4855,
      cover: "/covers/loved-child.png",
      colors: ["#40916c", "#1b4332"],
    },
    {
      id: "best-25-recession-proof-career-strat",
      title: "RECESSION-PROOF CAREER STRATEGIES AFTER COVID",
      titleKo: "코로나 이후 불황을 이기는 커리어 전략",
      author: "Jason Schenker",
      rightsHolder: "Rightol Media (Prestige Professional Publishing, LLC)",
      koreanPublisher: "다빈치하우스",
      country: "USA",
      pubYear: 2020,
      cumSold: 4684,
      cover: "/covers/career-strategy.png",
      colors: ["#3d5a80", "#1d3557"],
    },
    {
      id: "best-26-mastering-logical-fallacies",
      title: "MASTERING LOGICAL FALLACIES",
      titleKo: "일상의 무기가 되는 논리 수업",
      author: "Michael Withey",
      rightsHolder: "Callisto Media",
      koreanPublisher: "반니",
      country: "USA",
      pubYear: null,
      cumSold: 4491,
      cover: "/covers/logical-fallacies.png",
      colors: ["#7b2cbf", "#5a189a"],
    },
    {
      id: "best-27-speak-up",
      title: "SPEAK UP!",
      titleKo: "더 크게 소리쳐!",
      author: "Adora Svitak",
      rightsHolder: "Quarto",
      koreanPublisher: "특별한서재",
      country: "UK",
      pubYear: 2021,
      cumSold: 4103,
      cover: "/covers/speak-up.png",
      colors: ["#0077b6", "#03045e"],
    },
    {
      id: "best-28-future-of-finance-after-covi",
      title: "FUTURE OF FINANCE AFTER COVID, THE",
      titleKo: "금융의 미래",
      author: "Jason Schenker",
      rightsHolder: "Rightol Media (Prestige Professional Publishing, LLC)",
      koreanPublisher: "지니의 서재",
      country: "USA",
      pubYear: 2021,
      cumSold: 4007,
      cover: "/covers/future-of-finance.png",
      colors: ["#d62828", "#003049"],
    },
    {
      id: "best-29-kora-kerplunk-s-travelling-t",
      title: "KORA KERPLUNK'S TRAVELLING TONGUE",
      titleKo: "코라의 혀가 달아났어요!",
      author: "Emily S. Smith",
      rightsHolder: "BK Agency (Larrikin)",
      koreanPublisher: "피카주니어",
      country: "Australia",
      pubYear: 2023,
      cumSold: 3832,
      cover: "/covers/cora-tongue.png",
      colors: ["#606c38", "#283618"],
    },
    {
      id: "best-30-sheets-by-brenna-thummler",
      title: "SHEETS by Brenna Thummler",
      titleKo: "웬델 - 마음의 얼룩을 지워주는 마법 같은 친구",
      author: "Brenna Thummler",
      rightsHolder: "Webber Agency (Oni-Lion Forge)",
      koreanPublisher: "밝은미래",
      country: "USA",
      pubYear: 2020,
      cumSold: 3822,
      cover: "/covers/sheets-wendell.png",
      colors: ["#f4a261", "#e76f51"],
    },
  ],


  services: [
    {
      num: "01",
      title: "Korean rights",
      titleKo: "해외 저작물 수입",
      body: "We place Korean rights for international publishers and agents—from submission and negotiation through contracts and royalty reporting.",
      bodyKo: "양질의 해외 도서를 한국 출판사와 매칭합니다. 투고, 협상, 계약, 인세 관리까지.",
    },
    {
      num: "02",
      title: "Foreign rights",
      titleKo: "한국 저작물 수출",
      body: "We represent selected Korean titles for overseas markets and connect them with the right language partners.",
      bodyKo: "선별된 한국 도서를 해외에 소개하고, 언어권·파트너를 매칭합니다.",
    },
    {
      num: "03",
      title: "Co-production",
      titleKo: "공동제작",
      body: "We coordinate co-productions and co-editions for picture books and illustrated nonfiction, including shared print runs and production.",
      bodyKo: "그림책·일러스트 논픽션의 공동제작 코디네이션.",
    },
    {
      num: "04",
      title: "Other rights",
      titleKo: "기타 권리",
      body: "We are open to discussing all other rights—digital, audio, video, media, AI training, and more. Feel free to get in touch.",
      bodyKo: "디지털·오디오·영상·미디어·AI 학습 등 기타 권리에 대해 언제든 상담합니다. 편하게 문의해 주세요.",
    },
  ],

  news: [
    {
      date: "2026-03-12",
      tag: "Export",
      tagKo: "수출",
      title: "New Korean titles added to the export list",
      titleKo: "수출 목록에 한국 신작 추가",
      summary: "Picture book and essay titles now open for rights conversations.",
      summaryKo: "그림책·에세이 타이틀 권리 상담 개시.",
    },
    {
      date: "2026-01-28",
      tag: "Fair",
      tagKo: "북페어",
      title: "LENA Agency at Bologna 2026",
      titleKo: "레나에이전시, 볼로냐 2026 참가",
      summary: "Children’s and co-pro meetings — schedule requests open.",
      summaryKo: "아동·공동제작 미팅. 일정 요청 접수 중.",
    },
    {
      date: "2025-11-05",
      tag: "Export",
      tagKo: "수출",
      title: "Vietnamese edition under contract",
      titleKo: "한국 논픽션 베트남어판 계약",
      summary: "Outbound representation for a Korean education title.",
      summaryKo: "한국 교육·자기계발서 해외 계약 성사.",
    },
    {
      date: "2025-10-15",
      tag: "Fair",
      tagKo: "북페어",
      title: "Frankfurt Book Fair 2025 wrap",
      titleKo: "프랑크푸르트 도서전 2025",
      summary: "Strong interest in Korean nonfiction and picture books.",
      summaryKo: "한국 논픽션·그림책에 대한 높은 관심.",
    },
    {
      date: "2025-06-20",
      tag: "News",
      tagKo: "소식",
      title: "LENA Agency website launch",
      titleKo: "레나에이전시 웹사이트 오픈",
      summary: "Export catalog and agency introduction online.",
      summaryKo: "수출 카탈로그와 에이전시 소개 온라인 공개.",
    },
  ],
};

export type Lang = "ko" | "en";
